<?php

namespace AppBundle\Repository;

/**
 * ProfesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesorRepository extends \Doctrine\ORM\EntityRepository
{
}
