<?php

namespace AppBundle\Repository;

/**
 * VoluntarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoluntarioRepository extends \Doctrine\ORM\EntityRepository
{
}
